spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test # mysql compatible h2
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

dir:
  path: /Users/kimhyeonjin/advanced_cgv
