spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test;MODE=MySQL;DATABASE_TO_LOWER=TRUE;IGNORECASE=TRUE # mysql compatible h2
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create

dir:
  path: /Users/kimhyeonjin/advanced_cgv
